# Generated by Django 2.0.6 on 2018-06-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('SKU', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.IntegerField()),
                ('tank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='Constraint', to='app.Constraint'),
        ),
    ]
