# Generated by Django 2.0.6 on 2018-07-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('SKU', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=6)),
                ('variant', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=20)),
                ('time', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ratio', models.PositiveIntegerField(default=0)),
                ('skips', models.BooleanField(default=False)),
                ('strips', models.BooleanField(default=False)),
                ('tank', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Queued', max_length=10)),
                ('stn1', models.PositiveIntegerField(default=0)),
                ('stn2', models.PositiveIntegerField(default=0)),
                ('stn3', models.PositiveIntegerField(default=0)),
                ('stn4', models.PositiveIntegerField(default=0)),
                ('stn5', models.PositiveIntegerField(default=0)),
                ('stn6', models.PositiveIntegerField(default=0)),
                ('stn7', models.PositiveIntegerField(default=0)),
                ('stn8', models.PositiveIntegerField(default=0)),
                ('stn9', models.PositiveIntegerField(default=0)),
                ('stn10', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seq',
            fields=[
                ('Sq_No', models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Queued', max_length=10)),
                ('SKU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('A', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('B', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('C', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
            ],
        ),
    ]
