# Generated by Django 2.0.6 on 2018-07-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='status',
        ),
    ]
