# Generated by Django 2.0.6 on 2018-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
