# Generated by Django 2.0.6 on 2018-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seq',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Queued', max_length=10),
        ),
    ]
