# Generated by Django 2.0.6 on 2018-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='SKU',
        ),
        migrations.AddField(
            model_name='config',
            name='Station',
            field=models.ManyToManyField(to='app.Station'),
        ),
    ]
