# Generated by Django 2.0.6 on 2018-07-19 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='color',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Capital Alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Capital Alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='config',
            name='model',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only Alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='config',
            name='tank',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Capital Alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='config',
            name='variant',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Capital Alphabets are allowed.')]),
        ),
    ]
