# Generated by Django 2.0.6 on 2018-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180623_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
