# Generated by Django 2.0.6 on 2018-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_constraint_shift_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
