# Generated by Django 2.0.6 on 2018-07-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180705_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='Station',
            field=models.ManyToManyField(null=True, to='app.Station'),
        ),
    ]
