# Generated by Django 2.0.6 on 2018-07-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seq_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seq',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
    ]
