# Generated by Django 2.0.6 on 2018-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180718_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='A',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shift',
            name='B',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shift',
            name='C',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
    ]
