# Generated by Django 2.0.6 on 2018-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180718_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='SKU',
        ),
        migrations.AddField(
            model_name='config',
            name='stn1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn10',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn7',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn8',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='stn9',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
