# Generated by Django 2.0.6 on 2018-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180716_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='constraints',
        ),
        migrations.AddField(
            model_name='config',
            name='skips',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='strips',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constraint',
            name='Color_Blocked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
