# Generated by Django 2.0.6 on 2018-07-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180705_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ratio',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
