# Generated by Django 2.0.6 on 2018-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_config_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('time', models.PositiveIntegerField(default=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='shift_time',
        ),
        migrations.AlterField(
            model_name='config',
            name='constraints',
            field=models.ManyToManyField(blank=True, null=True, related_name='Constraint', to='app.Constraint'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
