# Generated by Django 2.0.6 on 2018-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180626_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='Constraint', to='app.Constraint'),
        ),
    ]
