# Generated by Django 2.0.6 on 2018-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180705_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='ratio',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
