# Generated by Django 2.0.6 on 2018-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180626_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='stn_time',
            field=models.ManyToManyField(to='app.Station'),
        ),
    ]
