# Generated by Django 2.0.6 on 2018-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180718_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seq',
            name='id',
        ),
        migrations.AlterField(
            model_name='seq',
            name='Sq_No',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
