# Generated by Django 2.0.6 on 2018-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180705_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='model',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='config',
            name='tank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='variant',
            field=models.CharField(max_length=1),
        ),
    ]
