# Generated by Django 2.0.6 on 2018-07-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180718_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.AlterField(
            model_name='config',
            name='model',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='SKU',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Config'),
        ),
    ]
