# Generated by Django 2.0.6 on 2018-06-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_config_stn_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='stn_time',
            new_name='stn',
        ),
    ]
