# Generated by Django 2.0.6 on 2018-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180627_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
