# Generated by Django 2.0.6 on 2018-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180712_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.PositiveIntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn10',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn3',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn4',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn5',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn6',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn7',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn8',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn9',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
