# Generated by Django 2.0.6 on 2018-06-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180628_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
