# Generated by Django 2.0.6 on 2018-06-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180628_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='stn',
        ),
        migrations.AddField(
            model_name='station1',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station10',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station2',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station3',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station4',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station5',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station6',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station7',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station8',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
        migrations.AddField(
            model_name='station9',
            name='SKU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Config'),
        ),
    ]
