# Generated by Django 2.0.6 on 2018-06-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180628_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station10',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station3',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station4',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station5',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station6',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station7',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station8',
            name='name',
        ),
        migrations.RemoveField(
            model_name='station9',
            name='name',
        ),
    ]
